using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Microsoft.SharePoint.Client.NetCore
{
    public enum ListTemplateType
    {
        InvalidType = -1,
        NoListTemplate,
        GenericList = 100,
        DocumentLibrary,
        Survey,
        Links,
        Announcements,
        Contacts,
        Events,
        Tasks,
        DiscussionBoard,
        PictureLibrary,
        DataSources,
        WebTemplateCatalog,
        UserInformation,
        WebPartCatalog,
        ListTemplateCatalog,
        XMLForm,
        MasterPageCatalog,
        NoCodeWorkflows,
        WorkflowProcess,
        WebPageLibrary,
        CustomGrid,
        SolutionCatalog,
        NoCodePublic,
        ThemeCatalog,
        DesignCatalog,
        AppDataCatalog,
        DataConnectionLibrary = 130,
        WorkflowHistory = 140,
        GanttTasks = 150,
        HelpLibrary,
        AccessRequest = 160,
        TasksWithTimelineAndHierarchy = 171,
        MaintenanceLogs = 175,
        Meetings = 200,
        Agenda,
        MeetingUser,
        Decision = 204,
        MeetingObjective = 207,
        TextBox = 210,
        ThingsToBring,
        HomePageLibrary,
        Posts = 301,
        Comments,
        Categories,
        Facility = 402,
        Whereabouts,
        CallTrack,
        Circulation,
        Timecard = 420,
        Holidays,
        IMEDic = 499,
        ExternalList = 600,
        MySiteDocumentLibrary = 700,
        IssueTracking = 1100,
        AdminTasks = 1200,
        HealthRules = 1220,
        HealthReports,
        DeveloperSiteDraftApps = 1230,
        AccessApp = 3100,
        AlchemyMobileForm,
        AlchemyApprovalWorkflow,
        SharingLinks = 3300,
        HashtagStore = 3400,
        ItemReferenceCollection = 3500,
        ItemReferenceReference,
        ItemReferenceReferenceCollection
    }
}
